tag_prefix = "v"
from_latest_tag = true
ignore_merge_commits = true
branch_whitelist = ["main"]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "TudorAndrei"
repository = "barrs"
